// GENERATED by tools/gen_layout_dump.py from subcraft_protocol.h: do not edit.
// Prints protocol/layout.json (constants, enum values, struct sizes and field offsets as the C++
// compiler sees them). tools/check_layout.sh regenerates this file and the JSON and fails if
// either committed copy differs; the Java, C# and Python layout tests read the committed JSON.
#include "subcraft_protocol.h"

#include <cstddef>
#include <cstdio>

using namespace subcraft::proto;

static bool first = true;

static void begin(const char* name)
{
	std::printf("%s\n    \"%s\": {", first ? "" : ",", name);
	first = false;
}

static void value(bool& firstValue, const char* name, unsigned long long v)
{
	std::printf("%s\"%s\": %llu", firstValue ? "" : ", ", name, v);
	firstValue = false;
}

#define C(name) std::printf("%s\n    \"%s\": %llu", first ? "" : ",", #name, (unsigned long long)(name)), first = false

int main()
{
	std::printf("{\n  \"version\": %u,\n  \"constants\": {", kVersion);
	C(kMagic);
	C(kVersion);
	C(kHeartbeatTimeoutNs);
	C(kOffHeader);
	C(kOffHostState);
	C(kOffMcState);
	C(kOffOverlayCtl);
	C(kOffOverlaySlotHdr);
	C(kOffCommandBox);
	C(kOffInputRing);
	C(kOffCreatureTable);
	C(kOffMobTable);
	C(kOffEventRing);
	C(kOffCollisionRing);
	C(kCollisionRingBytes);
	C(kOffOverlayPixels);
	C(kMaxOverlayW);
	C(kMaxOverlayH);
	C(kOverlaySlotBytes);
	C(kOverlaySlots);
	C(kOffRenderRing);
	C(kRenderRingBytes);
	C(kMappingBytes);
	C(kOverlayDirty);
	C(kCommandTextBytes);
	C(kCommandReplyBytes);
	C(kInputRingEntries);
	C(kInputRingHeadOff);
	C(kInputRingTailOff);
	C(kInputRingDataOff);
	C(kMaxCreatures);
	C(kMaxMobs);
	C(kEventRingEntries);
	C(kEventRingHeadOff);
	C(kEventRingTailOff);
	C(kEventRingDataOff);
	C(kColRingHeadOff);
	C(kColRingTailOff);
	C(kColRingDataOff);
	C(kColRingDataBytes);
	C(kBiomeCells);
	C(kBiomeUnknown);
	C(kTriMaterialShift);
	C(kRenRingHeadOff);
	C(kRenRingTailOff);
	C(kRenRingDataOff);
	C(kRenRingDataBytes);
	C(kDumpMagic);
	C(kRenDoubleSided);
	std::printf("\n  },\n  \"enums\": {");
	first = true;
	begin("HostFlags");
	{
		bool f = true;
		value(f, "kHostInGame", (unsigned long long)(HostFlags::kHostInGame));
		value(f, "kHostMenuOpen", (unsigned long long)(HostFlags::kHostMenuOpen));
		value(f, "kHostLoading", (unsigned long long)(HostFlags::kHostLoading));
		value(f, "kHostUnderwater", (unsigned long long)(HostFlags::kHostUnderwater));
		value(f, "kHostInside", (unsigned long long)(HostFlags::kHostInside));
		value(f, "kHostUnifiedHud", (unsigned long long)(HostFlags::kHostUnifiedHud));
	}
	std::printf("}");
	begin("McFlags");
	{
		bool f = true;
		value(f, "kMcInWorld", (unsigned long long)(McFlags::kMcInWorld));
		value(f, "kMcScreenOpen", (unsigned long long)(McFlags::kMcScreenOpen));
		value(f, "kMcOnGround", (unsigned long long)(McFlags::kMcOnGround));
		value(f, "kMcSneaking", (unsigned long long)(McFlags::kMcSneaking));
		value(f, "kMcSprinting", (unsigned long long)(McFlags::kMcSprinting));
		value(f, "kMcDead", (unsigned long long)(McFlags::kMcDead));
		value(f, "kMcSwimming", (unsigned long long)(McFlags::kMcSwimming));
		value(f, "kMcFlying", (unsigned long long)(McFlags::kMcFlying));
		value(f, "kMcInWater", (unsigned long long)(McFlags::kMcInWater));
		value(f, "kMcEyeInWater", (unsigned long long)(McFlags::kMcEyeInWater));
		value(f, "kMcLookCaptured", (unsigned long long)(McFlags::kMcLookCaptured));
	}
	std::printf("}");
	begin("InputType");
	{
		bool f = true;
		value(f, "kInKey", (unsigned long long)(InputType::kInKey));
		value(f, "kInMouseButton", (unsigned long long)(InputType::kInMouseButton));
		value(f, "kInScroll", (unsigned long long)(InputType::kInScroll));
		value(f, "kInCursor", (unsigned long long)(InputType::kInCursor));
		value(f, "kInText", (unsigned long long)(InputType::kInText));
		value(f, "kInReleaseAll", (unsigned long long)(InputType::kInReleaseAll));
		value(f, "kInHurt", (unsigned long long)(InputType::kInHurt));
		value(f, "kInOpenMenu", (unsigned long long)(InputType::kInOpenMenu));
		value(f, "kInLook", (unsigned long long)(InputType::kInLook));
		value(f, "kInHurtMob", (unsigned long long)(InputType::kInHurtMob));
	}
	std::printf("}");
	begin("HurtKind");
	{
		bool f = true;
		value(f, "kHurtMelee", (unsigned long long)(HurtKind::kHurtMelee));
		value(f, "kHurtProjectile", (unsigned long long)(HurtKind::kHurtProjectile));
		value(f, "kHurtOther", (unsigned long long)(HurtKind::kHurtOther));
	}
	std::printf("}");
	begin("HurtFlags");
	{
		bool f = true;
		value(f, "kHurtGrab", (unsigned long long)(HurtFlags::kHurtGrab));
	}
	std::printf("}");
	begin("CreatureFlags");
	{
		bool f = true;
		value(f, "kCreatureHostile", (unsigned long long)(CreatureFlags::kCreatureHostile));
		value(f, "kCreatureDead", (unsigned long long)(CreatureFlags::kCreatureDead));
		value(f, "kCreatureInvulnerable", (unsigned long long)(CreatureFlags::kCreatureInvulnerable));
		value(f, "kCreatureObject", (unsigned long long)(CreatureFlags::kCreatureObject));
	}
	std::printf("}");
	begin("MobFlags");
	{
		bool f = true;
		value(f, "kMobHostile", (unsigned long long)(MobFlags::kMobHostile));
	}
	std::printf("}");
	begin("McEventType");
	{
		bool f = true;
		value(f, "kEvHitCreature", (unsigned long long)(McEventType::kEvHitCreature));
		value(f, "kEvPlayerDied", (unsigned long long)(McEventType::kEvPlayerDied));
		value(f, "kEvExplosion", (unsigned long long)(McEventType::kEvExplosion));
		value(f, "kEvDebugResult", (unsigned long long)(McEventType::kEvDebugResult));
		value(f, "kEvSoundPlay", (unsigned long long)(McEventType::kEvSoundPlay));
		value(f, "kEvSoundUpdate", (unsigned long long)(McEventType::kEvSoundUpdate));
		value(f, "kEvSoundStop", (unsigned long long)(McEventType::kEvSoundStop));
		value(f, "kEvGrab", (unsigned long long)(McEventType::kEvGrab));
	}
	std::printf("}");
	begin("GrabFlags");
	{
		bool f = true;
		value(f, "kGrabHold", (unsigned long long)(GrabFlags::kGrabHold));
		value(f, "kGrabRelease", (unsigned long long)(GrabFlags::kGrabRelease));
		value(f, "kGrabLock", (unsigned long long)(GrabFlags::kGrabLock));
	}
	std::printf("}");
	begin("SoundFlags");
	{
		bool f = true;
		value(f, "kSoundRelative", (unsigned long long)(SoundFlags::kSoundRelative));
		value(f, "kSoundLoop", (unsigned long long)(SoundFlags::kSoundLoop));
		value(f, "kSoundUi", (unsigned long long)(SoundFlags::kSoundUi));
	}
	std::printf("}");
	begin("ColType");
	{
		bool f = true;
		value(f, "kColPad", (unsigned long long)(ColType::kColPad));
		value(f, "kColClear", (unsigned long long)(ColType::kColClear));
		value(f, "kColRegion", (unsigned long long)(ColType::kColRegion));
		value(f, "kColTris", (unsigned long long)(ColType::kColTris));
		value(f, "kColDry", (unsigned long long)(ColType::kColDry));
		value(f, "kColBiomes", (unsigned long long)(ColType::kColBiomes));
	}
	std::printf("}");
	begin("ColMaterial");
	{
		bool f = true;
		value(f, "kMatUnknown", (unsigned long long)(ColMaterial::kMatUnknown));
		value(f, "kMatRock", (unsigned long long)(ColMaterial::kMatRock));
		value(f, "kMatSand", (unsigned long long)(ColMaterial::kMatSand));
		value(f, "kMatCoral", (unsigned long long)(ColMaterial::kMatCoral));
		value(f, "kMatMetal", (unsigned long long)(ColMaterial::kMatMetal));
		value(f, "kMatGlass", (unsigned long long)(ColMaterial::kMatGlass));
		value(f, "kMatOrganic", (unsigned long long)(ColMaterial::kMatOrganic));
		value(f, "kMatIce", (unsigned long long)(ColMaterial::kMatIce));
		value(f, "kMatPrecursor", (unsigned long long)(ColMaterial::kMatPrecursor));
	}
	std::printf("}");
	begin("ColTriFlags");
	{
		bool f = true;
		value(f, "kTriStructure", (unsigned long long)(ColTriFlags::kTriStructure));
		value(f, "kTriTerrain", (unsigned long long)(ColTriFlags::kTriTerrain));
	}
	std::printf("}");
	begin("RenType");
	{
		bool f = true;
		value(f, "kRenPad", (unsigned long long)(RenType::kRenPad));
		value(f, "kRenAtlas", (unsigned long long)(RenType::kRenAtlas));
		value(f, "kRenSection", (unsigned long long)(RenType::kRenSection));
		value(f, "kRenClearAll", (unsigned long long)(RenType::kRenClearAll));
		value(f, "kRenTexture", (unsigned long long)(RenType::kRenTexture));
		value(f, "kRenScene", (unsigned long long)(RenType::kRenScene));
		value(f, "kRenAtlasRegion", (unsigned long long)(RenType::kRenAtlasRegion));
		value(f, "kRenLights", (unsigned long long)(RenType::kRenLights));
		value(f, "kRenHand", (unsigned long long)(RenType::kRenHand));
		value(f, "kRenSubLevel", (unsigned long long)(RenType::kRenSubLevel));
		value(f, "kRenSound", (unsigned long long)(RenType::kRenSound));
		value(f, "kRenColliders", (unsigned long long)(RenType::kRenColliders));
	}
	std::printf("}");
	begin("RenMaterial");
	{
		bool f = true;
		value(f, "kMatOpaque", (unsigned long long)(RenMaterial::kMatOpaque));
		value(f, "kMatCutout", (unsigned long long)(RenMaterial::kMatCutout));
		value(f, "kMatTranslucent", (unsigned long long)(RenMaterial::kMatTranslucent));
		value(f, "kMatEmissive", (unsigned long long)(RenMaterial::kMatEmissive));
		value(f, "kMatAdditive", (unsigned long long)(RenMaterial::kMatAdditive));
	}
	std::printf("}");
	begin("LightKind");
	{
		bool f = true;
		value(f, "kLightSteady", (unsigned long long)(LightKind::kLightSteady));
		value(f, "kLightFlame", (unsigned long long)(LightKind::kLightFlame));
		value(f, "kLightLava", (unsigned long long)(LightKind::kLightLava));
	}
	std::printf("}");
	std::printf("\n  },\n  \"structs\": {");
	first = true;
	begin("Header");
	std::printf("\"size\": %zu, \"fields\": {", sizeof(Header));
	{
		bool f = true;
		value(f, "magic", offsetof(Header, magic));
		value(f, "version", offsetof(Header, version));
		value(f, "hostPid", offsetof(Header, hostPid));
		value(f, "mcPid", offsetof(Header, mcPid));
		value(f, "hostHeartbeatNs", offsetof(Header, hostHeartbeatNs));
		value(f, "mcHeartbeatNs", offsetof(Header, mcHeartbeatNs));
	}
	std::printf("}}");
	begin("HostState");
	std::printf("\"size\": %zu, \"fields\": {", sizeof(HostState));
	{
		bool f = true;
		value(f, "seq", offsetof(HostState, seq));
		value(f, "flags", offsetof(HostState, flags));
		value(f, "worldId", offsetof(HostState, worldId));
		value(f, "collisionEpoch", offsetof(HostState, collisionEpoch));
		value(f, "posX", offsetof(HostState, posX));
		value(f, "posY", offsetof(HostState, posY));
		value(f, "posZ", offsetof(HostState, posZ));
		value(f, "yaw", offsetof(HostState, yaw));
		value(f, "pitch", offsetof(HostState, pitch));
		value(f, "teleportSeq", offsetof(HostState, teleportSeq));
		value(f, "viewportW", offsetof(HostState, viewportW));
		value(f, "viewportH", offsetof(HostState, viewportH));
		value(f, "dayFraction", offsetof(HostState, dayFraction));
		value(f, "oxygen", offsetof(HostState, oxygen));
		value(f, "oxygenCapacity", offsetof(HostState, oxygenCapacity));
		value(f, "reserved", offsetof(HostState, reserved));
	}
	std::printf("}}");
	begin("McState");
	std::printf("\"size\": %zu, \"fields\": {", sizeof(McState));
	{
		bool f = true;
		value(f, "seq", offsetof(McState, seq));
		value(f, "flags", offsetof(McState, flags));
		value(f, "x", offsetof(McState, x));
		value(f, "y", offsetof(McState, y));
		value(f, "z", offsetof(McState, z));
		value(f, "yaw", offsetof(McState, yaw));
		value(f, "pitch", offsetof(McState, pitch));
		value(f, "eyeHeight", offsetof(McState, eyeHeight));
		value(f, "sensitivity", offsetof(McState, sensitivity));
		value(f, "teleportAck", offsetof(McState, teleportAck));
		value(f, "guiScale", offsetof(McState, guiScale));
		value(f, "frameCounter", offsetof(McState, frameCounter));
		value(f, "fovDeg", offsetof(McState, fovDeg));
		value(f, "bobPhase", offsetof(McState, bobPhase));
		value(f, "bobAmount", offsetof(McState, bobAmount));
		value(f, "handFovDeg", offsetof(McState, handFovDeg));
		value(f, "eyeX", offsetof(McState, eyeX));
		value(f, "eyeY", offsetof(McState, eyeY));
		value(f, "eyeZ", offsetof(McState, eyeZ));
		value(f, "tickNs", offsetof(McState, tickNs));
		value(f, "prevX", offsetof(McState, prevX));
		value(f, "prevY", offsetof(McState, prevY));
		value(f, "prevZ", offsetof(McState, prevZ));
		value(f, "curX", offsetof(McState, curX));
		value(f, "curY", offsetof(McState, curY));
		value(f, "curZ", offsetof(McState, curZ));
		value(f, "tickEyeO", offsetof(McState, tickEyeO));
		value(f, "tickEye", offsetof(McState, tickEye));
		value(f, "walkDistO", offsetof(McState, walkDistO));
		value(f, "walkDist", offsetof(McState, walkDist));
		value(f, "bobO", offsetof(McState, bobO));
		value(f, "bob", offsetof(McState, bob));
		value(f, "tickMs", offsetof(McState, tickMs));
		value(f, "tickPad", offsetof(McState, tickPad));
		value(f, "cameraMode", offsetof(McState, cameraMode));
		value(f, "cameraDistance", offsetof(McState, cameraDistance));
		value(f, "health", offsetof(McState, health));
		value(f, "maxHealth", offsetof(McState, maxHealth));
		value(f, "food", offsetof(McState, food));
		value(f, "saturation", offsetof(McState, saturation));
		value(f, "air", offsetof(McState, air));
		value(f, "maxAir", offsetof(McState, maxAir));
		value(f, "hurtTiltDeg", offsetof(McState, hurtTiltDeg));
		value(f, "hurtDirDeg", offsetof(McState, hurtDirDeg));
		value(f, "deathRollDeg", offsetof(McState, deathRollDeg));
		value(f, "hurtPad", offsetof(McState, hurtPad));
	}
	std::printf("}}");
	begin("OverlayCtl");
	std::printf("\"size\": %zu, \"fields\": {", sizeof(OverlayCtl));
	{
		bool f = true;
		value(f, "state", offsetof(OverlayCtl, state));
		value(f, "pad", offsetof(OverlayCtl, pad));
		value(f, "framesPublished", offsetof(OverlayCtl, framesPublished));
	}
	std::printf("}}");
	begin("OverlaySlotHdr");
	std::printf("\"size\": %zu, \"fields\": {", sizeof(OverlaySlotHdr));
	{
		bool f = true;
		value(f, "width", offsetof(OverlaySlotHdr, width));
		value(f, "height", offsetof(OverlaySlotHdr, height));
		value(f, "flags", offsetof(OverlaySlotHdr, flags));
		value(f, "pad", offsetof(OverlaySlotHdr, pad));
		value(f, "frameId", offsetof(OverlaySlotHdr, frameId));
		value(f, "reserved", offsetof(OverlaySlotHdr, reserved));
	}
	std::printf("}}");
	begin("CommandBox");
	std::printf("\"size\": %zu, \"fields\": {", sizeof(CommandBox));
	{
		bool f = true;
		value(f, "seq", offsetof(CommandBox, seq));
		value(f, "ack", offsetof(CommandBox, ack));
		value(f, "status", offsetof(CommandBox, status));
		value(f, "textLen", offsetof(CommandBox, textLen));
		value(f, "text", offsetof(CommandBox, text));
		value(f, "reply", offsetof(CommandBox, reply));
	}
	std::printf("}}");
	begin("InputEvent");
	std::printf("\"size\": %zu, \"fields\": {", sizeof(InputEvent));
	{
		bool f = true;
		value(f, "type", offsetof(InputEvent, type));
		value(f, "code", offsetof(InputEvent, code));
		value(f, "a", offsetof(InputEvent, a));
		value(f, "b", offsetof(InputEvent, b));
		value(f, "c", offsetof(InputEvent, c));
	}
	std::printf("}}");
	begin("CreatureRecord");
	std::printf("\"size\": %zu, \"fields\": {", sizeof(CreatureRecord));
	{
		bool f = true;
		value(f, "id", offsetof(CreatureRecord, id));
		value(f, "flags", offsetof(CreatureRecord, flags));
		value(f, "x", offsetof(CreatureRecord, x));
		value(f, "y", offsetof(CreatureRecord, y));
		value(f, "z", offsetof(CreatureRecord, z));
		value(f, "yaw", offsetof(CreatureRecord, yaw));
		value(f, "width", offsetof(CreatureRecord, width));
		value(f, "height", offsetof(CreatureRecord, height));
		value(f, "healthFrac", offsetof(CreatureRecord, healthFrac));
		value(f, "pad", offsetof(CreatureRecord, pad));
		value(f, "name", offsetof(CreatureRecord, name));
	}
	std::printf("}}");
	begin("CreatureTable");
	std::printf("\"size\": %zu, \"fields\": {", sizeof(CreatureTable));
	{
		bool f = true;
		value(f, "seq", offsetof(CreatureTable, seq));
		value(f, "count", offsetof(CreatureTable, count));
		value(f, "pad", offsetof(CreatureTable, pad));
		value(f, "creatures", offsetof(CreatureTable, creatures));
	}
	std::printf("}}");
	begin("MobRecord");
	std::printf("\"size\": %zu, \"fields\": {", sizeof(MobRecord));
	{
		bool f = true;
		value(f, "id", offsetof(MobRecord, id));
		value(f, "flags", offsetof(MobRecord, flags));
		value(f, "x", offsetof(MobRecord, x));
		value(f, "y", offsetof(MobRecord, y));
		value(f, "z", offsetof(MobRecord, z));
		value(f, "width", offsetof(MobRecord, width));
		value(f, "height", offsetof(MobRecord, height));
		value(f, "healthFrac", offsetof(MobRecord, healthFrac));
	}
	std::printf("}}");
	begin("MobTable");
	std::printf("\"size\": %zu, \"fields\": {", sizeof(MobTable));
	{
		bool f = true;
		value(f, "seq", offsetof(MobTable, seq));
		value(f, "count", offsetof(MobTable, count));
		value(f, "pad", offsetof(MobTable, pad));
		value(f, "mobs", offsetof(MobTable, mobs));
	}
	std::printf("}}");
	begin("McEvent");
	std::printf("\"size\": %zu, \"fields\": {", sizeof(McEvent));
	{
		bool f = true;
		value(f, "type", offsetof(McEvent, type));
		value(f, "id", offsetof(McEvent, id));
		value(f, "a", offsetof(McEvent, a));
		value(f, "b", offsetof(McEvent, b));
		value(f, "c", offsetof(McEvent, c));
		value(f, "d", offsetof(McEvent, d));
		value(f, "flags", offsetof(McEvent, flags));
		value(f, "extra", offsetof(McEvent, extra));
	}
	std::printf("}}");
	begin("ColBiomes");
	std::printf("\"size\": %zu, \"fields\": {", sizeof(ColBiomes));
	{
		bool f = true;
		value(f, "sx", offsetof(ColBiomes, sx));
		value(f, "sy", offsetof(ColBiomes, sy));
		value(f, "sz", offsetof(ColBiomes, sz));
		value(f, "nameCount", offsetof(ColBiomes, nameCount));
		value(f, "pad", offsetof(ColBiomes, pad));
	}
	std::printf("}}");
	begin("ColMsgHeader");
	std::printf("\"size\": %zu, \"fields\": {", sizeof(ColMsgHeader));
	{
		bool f = true;
		value(f, "type", offsetof(ColMsgHeader, type));
		value(f, "payloadBytes", offsetof(ColMsgHeader, payloadBytes));
	}
	std::printf("}}");
	begin("ColRegion");
	std::printf("\"size\": %zu, \"fields\": {", sizeof(ColRegion));
	{
		bool f = true;
		value(f, "minX", offsetof(ColRegion, minX));
		value(f, "minY", offsetof(ColRegion, minY));
		value(f, "minZ", offsetof(ColRegion, minZ));
		value(f, "maxX", offsetof(ColRegion, maxX));
		value(f, "maxY", offsetof(ColRegion, maxY));
		value(f, "maxZ", offsetof(ColRegion, maxZ));
		value(f, "epoch", offsetof(ColRegion, epoch));
		value(f, "count", offsetof(ColRegion, count));
	}
	std::printf("}}");
	begin("ColTri");
	std::printf("\"size\": %zu, \"fields\": {", sizeof(ColTri));
	{
		bool f = true;
		value(f, "v", offsetof(ColTri, v));
		value(f, "flags", offsetof(ColTri, flags));
	}
	std::printf("}}");
	begin("ColDryHeader");
	std::printf("\"size\": %zu, \"fields\": {", sizeof(ColDryHeader));
	{
		bool f = true;
		value(f, "epoch", offsetof(ColDryHeader, epoch));
		value(f, "count", offsetof(ColDryHeader, count));
	}
	std::printf("}}");
	begin("DryBox");
	std::printf("\"size\": %zu, \"fields\": {", sizeof(DryBox));
	{
		bool f = true;
		value(f, "minX", offsetof(DryBox, minX));
		value(f, "minY", offsetof(DryBox, minY));
		value(f, "minZ", offsetof(DryBox, minZ));
		value(f, "maxX", offsetof(DryBox, maxX));
		value(f, "maxY", offsetof(DryBox, maxY));
		value(f, "maxZ", offsetof(DryBox, maxZ));
		value(f, "id", offsetof(DryBox, id));
		value(f, "flags", offsetof(DryBox, flags));
	}
	std::printf("}}");
	begin("ColBlock");
	std::printf("\"size\": %zu, \"fields\": {", sizeof(ColBlock));
	{
		bool f = true;
		value(f, "x", offsetof(ColBlock, x));
		value(f, "y", offsetof(ColBlock, y));
		value(f, "z", offsetof(ColBlock, z));
		value(f, "material", offsetof(ColBlock, material));
		value(f, "flags", offsetof(ColBlock, flags));
		value(f, "pad", offsetof(ColBlock, pad));
		value(f, "bits", offsetof(ColBlock, bits));
	}
	std::printf("}}");
	begin("RenAtlas");
	std::printf("\"size\": %zu, \"fields\": {", sizeof(RenAtlas));
	{
		bool f = true;
		value(f, "width", offsetof(RenAtlas, width));
		value(f, "height", offsetof(RenAtlas, height));
	}
	std::printf("}}");
	begin("RenAtlasRegion");
	std::printf("\"size\": %zu, \"fields\": {", sizeof(RenAtlasRegion));
	{
		bool f = true;
		value(f, "x", offsetof(RenAtlasRegion, x));
		value(f, "y", offsetof(RenAtlasRegion, y));
		value(f, "width", offsetof(RenAtlasRegion, width));
		value(f, "height", offsetof(RenAtlasRegion, height));
	}
	std::printf("}}");
	begin("RenTexture");
	std::printf("\"size\": %zu, \"fields\": {", sizeof(RenTexture));
	{
		bool f = true;
		value(f, "id", offsetof(RenTexture, id));
		value(f, "width", offsetof(RenTexture, width));
		value(f, "height", offsetof(RenTexture, height));
		value(f, "pad", offsetof(RenTexture, pad));
	}
	std::printf("}}");
	begin("RenSection");
	std::printf("\"size\": %zu, \"fields\": {", sizeof(RenSection));
	{
		bool f = true;
		value(f, "sx", offsetof(RenSection, sx));
		value(f, "sy", offsetof(RenSection, sy));
		value(f, "sz", offsetof(RenSection, sz));
		value(f, "vertexCount", offsetof(RenSection, vertexCount));
	}
	std::printf("}}");
	begin("RenScene");
	std::printf("\"size\": %zu, \"fields\": {", sizeof(RenScene));
	{
		bool f = true;
		value(f, "originX", offsetof(RenScene, originX));
		value(f, "originY", offsetof(RenScene, originY));
		value(f, "originZ", offsetof(RenScene, originZ));
		value(f, "batchCount", offsetof(RenScene, batchCount));
		value(f, "vertexCount", offsetof(RenScene, vertexCount));
	}
	std::printf("}}");
	begin("RenBatch");
	std::printf("\"size\": %zu, \"fields\": {", sizeof(RenBatch));
	{
		bool f = true;
		value(f, "texture", offsetof(RenBatch, texture));
		value(f, "first", offsetof(RenBatch, first));
		value(f, "count", offsetof(RenBatch, count));
		value(f, "material", offsetof(RenBatch, material));
	}
	std::printf("}}");
	begin("RenVertex");
	std::printf("\"size\": %zu, \"fields\": {", sizeof(RenVertex));
	{
		bool f = true;
		value(f, "x", offsetof(RenVertex, x));
		value(f, "y", offsetof(RenVertex, y));
		value(f, "z", offsetof(RenVertex, z));
		value(f, "u", offsetof(RenVertex, u));
		value(f, "v", offsetof(RenVertex, v));
		value(f, "color", offsetof(RenVertex, color));
		value(f, "light", offsetof(RenVertex, light));
		value(f, "flags", offsetof(RenVertex, flags));
	}
	std::printf("}}");
	begin("RenLights");
	std::printf("\"size\": %zu, \"fields\": {", sizeof(RenLights));
	{
		bool f = true;
		value(f, "sx", offsetof(RenLights, sx));
		value(f, "sy", offsetof(RenLights, sy));
		value(f, "sz", offsetof(RenLights, sz));
		value(f, "count", offsetof(RenLights, count));
	}
	std::printf("}}");
	begin("RenColliders");
	std::printf("\"size\": %zu, \"fields\": {", sizeof(RenColliders));
	{
		bool f = true;
		value(f, "sx", offsetof(RenColliders, sx));
		value(f, "sy", offsetof(RenColliders, sy));
		value(f, "sz", offsetof(RenColliders, sz));
		value(f, "count", offsetof(RenColliders, count));
	}
	std::printf("}}");
	begin("RenSubLevel");
	std::printf("\"size\": %zu, \"fields\": {", sizeof(RenSubLevel));
	{
		bool f = true;
		value(f, "id", offsetof(RenSubLevel, id));
		value(f, "flags", offsetof(RenSubLevel, flags));
		value(f, "minSx", offsetof(RenSubLevel, minSx));
		value(f, "minSy", offsetof(RenSubLevel, minSy));
		value(f, "minSz", offsetof(RenSubLevel, minSz));
		value(f, "maxSx", offsetof(RenSubLevel, maxSx));
		value(f, "maxSy", offsetof(RenSubLevel, maxSy));
		value(f, "maxSz", offsetof(RenSubLevel, maxSz));
		value(f, "posX", offsetof(RenSubLevel, posX));
		value(f, "posY", offsetof(RenSubLevel, posY));
		value(f, "posZ", offsetof(RenSubLevel, posZ));
		value(f, "rotX", offsetof(RenSubLevel, rotX));
		value(f, "rotY", offsetof(RenSubLevel, rotY));
		value(f, "rotZ", offsetof(RenSubLevel, rotZ));
		value(f, "rotW", offsetof(RenSubLevel, rotW));
		value(f, "pivotX", offsetof(RenSubLevel, pivotX));
		value(f, "pivotY", offsetof(RenSubLevel, pivotY));
		value(f, "pivotZ", offsetof(RenSubLevel, pivotZ));
		value(f, "scaleX", offsetof(RenSubLevel, scaleX));
		value(f, "scaleY", offsetof(RenSubLevel, scaleY));
		value(f, "scaleZ", offsetof(RenSubLevel, scaleZ));
	}
	std::printf("}}");
	begin("RenSound");
	std::printf("\"size\": %zu, \"fields\": {", sizeof(RenSound));
	{
		bool f = true;
		value(f, "id", offsetof(RenSound, id));
		value(f, "bytes", offsetof(RenSound, bytes));
		value(f, "pad", offsetof(RenSound, pad));
	}
	std::printf("}}");
	begin("RenBox");
	std::printf("\"size\": %zu, \"fields\": {", sizeof(RenBox));
	{
		bool f = true;
		value(f, "minX", offsetof(RenBox, minX));
		value(f, "minY", offsetof(RenBox, minY));
		value(f, "minZ", offsetof(RenBox, minZ));
		value(f, "maxX", offsetof(RenBox, maxX));
		value(f, "maxY", offsetof(RenBox, maxY));
		value(f, "maxZ", offsetof(RenBox, maxZ));
	}
	std::printf("}}");
	begin("RenLight");
	std::printf("\"size\": %zu, \"fields\": {", sizeof(RenLight));
	{
		bool f = true;
		value(f, "x", offsetof(RenLight, x));
		value(f, "y", offsetof(RenLight, y));
		value(f, "z", offsetof(RenLight, z));
		value(f, "level", offsetof(RenLight, level));
		value(f, "color", offsetof(RenLight, color));
	}
	std::printf("}}");
	std::printf("\n  }\n}\n");
	return 0;
}
