"""Generates protocol/layout_dump.cpp from protocol/subcraft_protocol.h.

layout_dump.cpp prints protocol/layout.json: every numeric constant, every enum value and every
struct field offset, as the C++ compiler sees them. This script only finds the *names* (a small
parser for the header's restricted C++: `inline constexpr` constants, `enum Name : type { ... }`,
and `struct Name { ... }` of plain fields); the values and offsets always come from the compiler.
So a field or enum added to the header can't be forgotten in the layout tests.

    python3 tools/gen_layout_dump.py           # rewrite protocol/layout_dump.cpp
    python3 tools/gen_layout_dump.py --check   # exit 1 if it is stale (tools/check_layout.sh runs this)

Python 3.9+, standard library only.
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HEADER = os.path.join(ROOT, "protocol", "subcraft_protocol.h")
OUT = os.path.join(ROOT, "protocol", "layout_dump.cpp")


def strip_comments(text):
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    return re.sub(r"//[^\n]*", "", text)


def parse(text):
    """Returns (constants, enums, structs): names in header order."""
    text = strip_comments(text)
    constants = []
    for m in re.finditer(r"inline\s+constexpr\s+([\w:]+)\s+(k\w+)\s*(\[\s*\])?\s*=", text):
        if m.group(3) is None and m.group(1) != "char":
            constants.append(m.group(2))
    enums = []
    for m in re.finditer(r"enum\s+(\w+)\s*:\s*[\w:]+\s*\{(.*?)\}\s*;", text, flags=re.S):
        members = [part.split("=")[0].strip() for part in m.group(2).split(",")]
        enums.append((m.group(1), [x for x in members if x]))
    structs = []
    for m in re.finditer(r"struct\s+(\w+)\s*\{(.*?)\}\s*;", text, flags=re.S):
        fields = []
        for decl in m.group(2).split(";"):
            decl = decl.strip()
            if not decl:
                continue
            # "std::uint32_t a, b;" / "float v[9];" / "CreatureRecord creatures[kMaxCreatures];"
            mm = re.match(r"([\w:]+)\s+(.+)$", decl, flags=re.S)
            if not mm:
                raise SystemExit(f"layout: can't parse field '{decl}' in struct {m.group(1)}")
            for name in mm.group(2).split(","):
                name = re.sub(r"\[.*?\]", "", name).strip()
                if not re.fullmatch(r"\w+", name):
                    raise SystemExit(f"layout: can't parse field '{decl}' in struct {m.group(1)}")
                fields.append(name)
        structs.append((m.group(1), fields))
    return constants, enums, structs


PROLOGUE = """// GENERATED by tools/gen_layout_dump.py from subcraft_protocol.h: do not edit.
// Prints protocol/layout.json (constants, enum values, struct sizes and field offsets as the C++
// compiler sees them). tools/check_layout.sh regenerates this file and the JSON and fails if
// either committed copy differs; the Java, C# and Python layout tests read the committed JSON.
#include "subcraft_protocol.h"

#include <cstddef>
#include <cstdio>

using namespace subcraft::proto;

static bool first = true;

static void begin(const char* name)
{
	std::printf("%s\\n    \\"%s\\": {", first ? "" : ",", name);
	first = false;
}

static void value(bool& firstValue, const char* name, unsigned long long v)
{
	std::printf("%s\\"%s\\": %llu", firstValue ? "" : ", ", name, v);
	firstValue = false;
}

#define C(name) std::printf("%s\\n    \\"%s\\": %llu", first ? "" : ",", #name, (unsigned long long)(name)), first = false

int main()
{
	std::printf("{\\n  \\"version\\": %u,\\n  \\"constants\\": {", kVersion);
"""


def render(constants, enums, structs):
    out = [PROLOGUE]
    for c in constants:
        out.append(f"\tC({c});\n")
    out.append('\tstd::printf("\\n  },\\n  \\"enums\\": {");\n\tfirst = true;\n')
    for name, members in enums:
        out.append(f"\tbegin(\"{name}\");\n\t{{\n\t\tbool f = true;\n")
        for m in members:
            out.append(f"\t\tvalue(f, \"{m}\", (unsigned long long)({name}::{m}));\n")
        out.append("\t}\n\tstd::printf(\"}\");\n")
    out.append('\tstd::printf("\\n  },\\n  \\"structs\\": {");\n\tfirst = true;\n')
    for name, fields in structs:
        out.append(f"\tbegin(\"{name}\");\n\tstd::printf(\"\\\"size\\\": %zu, \\\"fields\\\": {{\", sizeof({name}));\n")
        out.append("\t{\n\t\tbool f = true;\n")
        for fld in fields:
            out.append(f"\t\tvalue(f, \"{fld}\", offsetof({name}, {fld}));\n")
        out.append("\t}\n\tstd::printf(\"}}\");\n")
    out.append('\tstd::printf("\\n  }\\n}\\n");\n\treturn 0;\n}\n')
    return "".join(out)


def main():
    with open(HEADER, encoding="utf-8") as f:
        text = render(*parse(f.read()))
    if "--check" in sys.argv[1:]:
        with open(OUT, encoding="utf-8") as f:
            if f.read() != text:
                print("protocol/layout_dump.cpp is stale: run python3 tools/gen_layout_dump.py", file=sys.stderr)
                return 1
        print("layout_dump.cpp matches subcraft_protocol.h")
        return 0
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("wrote protocol/layout_dump.cpp")
    return 0


if __name__ == "__main__":
    sys.exit(main())
